---
- name: This is a hello-world example
  hosts: 192.168.10.10,192.168.10.11,192.168.10.12
  tasks:
  - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
    copy: content="hello world\n" dest=/tmp/testfile.txt
